/*
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: suishen/wolves/gdt/feedback/vo/postBody.proto

package com.learn.springbootzookeeper.config;

public final class GdtPostBody {
  private GdtPostBody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface postBodyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string clickId = 1;
    */
/**
     * <code>required string clickId = 1;</code>
     *
     * <pre>
     *点击ID
     * </pre>
     *//*
*/
/*//*

    boolean hasClickId();
    /**
     * <code>required string clickId = 1;</code>
     *
     * <pre>
     *点击ID
     * </pre>
     *//*

    String getClickId();
    */
/**
     * <code>required string clickId = 1;</code>
     *
     * <pre>
     *点击ID
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getClickIdBytes();

    // required string muid = 2;
    */
/**
     * <code>required string muid = 2;</code>
     *
     * <pre>
     *设备id
     * </pre>
     *//*

    boolean hasMuid();
    */
/**
     * <code>required string muid = 2;</code>
     *
     * <pre>
     *设备id
     * </pre>
     *//*

    String getMuid();
    */
/**
     * <code>required string muid = 2;</code>
     *
     * <pre>
     *设备id
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getMuidBytes();

    // required int32 appid = 3;
    */
/**
     * <code>required int32 appid = 3;</code>
     *
     * <pre>
     *Android为应用宝ID
     * </pre>
     *//*

    boolean hasAppid();
    */
/**
     * <code>required int32 appid = 3;</code>
     *
     * <pre>
     *Android为应用宝ID
     * </pre>
     *//*

    int getAppid();

    // required string convTime = 4;
    */
/**
     * <code>required string convTime = 4;</code>
     *
     * <pre>
     *转化发生时间,秒级
     * </pre>
     *//*

    boolean hasConvTime();
    */
/**
     * <code>required string convTime = 4;</code>
     *
     * <pre>
     *转化发生时间,秒级
     * </pre>
     *//*

    String getConvTime();
    */
/**
     * <code>required string convTime = 4;</code>
     *
     * <pre>
     *转化发生时间,秒级
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getConvTimeBytes();

    // required string clientIp = 5;
    */
/**
     * <code>required string clientIp = 5;</code>
     *
     * <pre>
     *转化发生用户的客户端IP
     * </pre>
     *//*

    boolean hasClientIp();
    */
/**
     * <code>required string clientIp = 5;</code>
     *
     * <pre>
     *转化发生用户的客户端IP
     * </pre>
     *//*

    String getClientIp();
    */
/**
     * <code>required string clientIp = 5;</code>
     *
     * <pre>
     *转化发生用户的客户端IP
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getClientIpBytes();

    // required string encstr = 6;
    */
/**
     * <code>required string encstr = 6;</code>
     *
     * <pre>
     *MD5后字符串
     * </pre>
     *//*

    boolean hasEncstr();
    */
/**
     * <code>required string encstr = 6;</code>
     *
     * <pre>
     *MD5后字符串
     * </pre>
     *//*

    String getEncstr();
    */
/**
     * <code>required string encstr = 6;</code>
     *
     * <pre>
     *MD5后字符串
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getEncstrBytes();

    // required string encver = 7;
    */
/**
     * <code>required string encver = 7;</code>
     *
     * <pre>
     *加密版本
     * </pre>
     *//*

    boolean hasEncver();
    */
/**
     * <code>required string encver = 7;</code>
     *
     * <pre>
     *加密版本
     * </pre>
     *//*

    String getEncver();
    */
/**
     * <code>required string encver = 7;</code>
     *
     * <pre>
     *加密版本
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getEncverBytes();

    // required int32 advertiserId = 8;
    */
/**
     * <code>required int32 advertiserId = 8;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     *//*

    boolean hasAdvertiserId();
    */
/**
     * <code>required int32 advertiserId = 8;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     *//*

    int getAdvertiserId();

    // required string appType = 9;
    */
/**
     * <code>required string appType = 9;</code>
     *
     * <pre>
     *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
     * </pre>
     *//*

    boolean hasAppType();
    */
/**
     * <code>required string appType = 9;</code>
     *
     * <pre>
     *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
     * </pre>
     *//*

    String getAppType();
    */
/**
     * <code>required string appType = 9;</code>
     *
     * <pre>
     *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getAppTypeBytes();

    // required string convType = 10;
    */
/**
     * <code>required string convType = 10;</code>
     *
     * <pre>
     *转化行为
     * </pre>
     *//*

    boolean hasConvType();
    */
/**
     * <code>required string convType = 10;</code>
     *
     * <pre>
     *转化行为
     * </pre>
     *//*

    String getConvType();
    */
/**
     * <code>required string convType = 10;</code>
     *
     * <pre>
     *转化行为
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getConvTypeBytes();

    // required int32 appKey = 11;
    */
/**
     * <code>required int32 appKey = 11;</code>
     *
     * <pre>
     *appkey
     * </pre>
     *//*

    boolean hasAppKey();
    */
/**
     * <code>required int32 appKey = 11;</code>
     *
     * <pre>
     *appkey
     * </pre>
     *//*

    int getAppKey();

    // required string devId = 12;
    */
/**
     * <code>required string devId = 12;</code>
     *
     * <pre>
     *device id
     * </pre>
     *//*

    boolean hasDevId();
    */
/**
     * <code>required string devId = 12;</code>
     *
     * <pre>
     *device id
     * </pre>
     *//*

    String getDevId();
    */
/**
     * <code>required string devId = 12;</code>
     *
     * <pre>
     *device id
     * </pre>
     *//*

    com.google.protobuf.ByteString
        getDevIdBytes();
  }
  */
/**
   * Protobuf type {@code postBody}
   *//*

  public static final class postBody extends
      com.google.protobuf.GeneratedMessage
      implements postBodyOrBuilder {
    // Use postBody.newBuilder() to construct.
    private postBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private postBody(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final postBody defaultInstance;
    public static postBody getDefaultInstance() {
      return defaultInstance;
    }

    public postBody getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private postBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clickId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              muid_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              appid_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              convTime_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              clientIp_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              encstr_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              encver_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              advertiserId_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              appType_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              convType_ = input.readBytes();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              appKey_ = input.readInt32();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              devId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return suishen.wolves.gdt.feedback.vo.GdtPostBody.internal_static_postBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return suishen.wolves.gdt.feedback.vo.GdtPostBody.internal_static_postBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody.class, suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody.Builder.class);
    }

    public static com.google.protobuf.Parser<postBody> PARSER =
        new com.google.protobuf.AbstractParser<postBody>() {
      public postBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new postBody(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<postBody> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string clickId = 1;
    public static final int CLICKID_FIELD_NUMBER = 1;
    private Object clickId_;
    */
/**
     * <code>required string clickId = 1;</code>
     *
     * <pre>
     *点击ID
     * </pre>
     *//*

    public boolean hasClickId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    */
/**
     * <code>required string clickId = 1;</code>
     *
     * <pre>
     *点击ID
     * </pre>
     *//*

    public String getClickId() {
      Object ref = clickId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clickId_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string clickId = 1;</code>
     *
     * <pre>
     *点击ID
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getClickIdBytes() {
      Object ref = clickId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clickId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string muid = 2;
    public static final int MUID_FIELD_NUMBER = 2;
    private Object muid_;
    */
/**
     * <code>required string muid = 2;</code>
     *
     * <pre>
     *设备id
     * </pre>
     *//*

    public boolean hasMuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    */
/**
     * <code>required string muid = 2;</code>
     *
     * <pre>
     *设备id
     * </pre>
     *//*

    public String getMuid() {
      Object ref = muid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          muid_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string muid = 2;</code>
     *
     * <pre>
     *设备id
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getMuidBytes() {
      Object ref = muid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        muid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 appid = 3;
    public static final int APPID_FIELD_NUMBER = 3;
    private int appid_;
    */
/**
     * <code>required int32 appid = 3;</code>
     *
     * <pre>
     *Android为应用宝ID
     * </pre>
     *//*

    public boolean hasAppid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    */
/**
     * <code>required int32 appid = 3;</code>
     *
     * <pre>
     *Android为应用宝ID
     * </pre>
     *//*

    public int getAppid() {
      return appid_;
    }

    // required string convTime = 4;
    public static final int CONVTIME_FIELD_NUMBER = 4;
    private Object convTime_;
    */
/**
     * <code>required string convTime = 4;</code>
     *
     * <pre>
     *转化发生时间,秒级
     * </pre>
     *//*

    public boolean hasConvTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    */
/**
     * <code>required string convTime = 4;</code>
     *
     * <pre>
     *转化发生时间,秒级
     * </pre>
     *//*

    public String getConvTime() {
      Object ref = convTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          convTime_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string convTime = 4;</code>
     *
     * <pre>
     *转化发生时间,秒级
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getConvTimeBytes() {
      Object ref = convTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        convTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string clientIp = 5;
    public static final int CLIENTIP_FIELD_NUMBER = 5;
    private Object clientIp_;
    */
/**
     * <code>required string clientIp = 5;</code>
     *
     * <pre>
     *转化发生用户的客户端IP
     * </pre>
     *//*

    public boolean hasClientIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    */
/**
     * <code>required string clientIp = 5;</code>
     *
     * <pre>
     *转化发生用户的客户端IP
     * </pre>
     *//*

    public String getClientIp() {
      Object ref = clientIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientIp_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string clientIp = 5;</code>
     *
     * <pre>
     *转化发生用户的客户端IP
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getClientIpBytes() {
      Object ref = clientIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string encstr = 6;
    public static final int ENCSTR_FIELD_NUMBER = 6;
    private Object encstr_;
    */
/**
     * <code>required string encstr = 6;</code>
     *
     * <pre>
     *MD5后字符串
     * </pre>
     *//*

    public boolean hasEncstr() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    */
/**
     * <code>required string encstr = 6;</code>
     *
     * <pre>
     *MD5后字符串
     * </pre>
     *//*

    public String getEncstr() {
      Object ref = encstr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encstr_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string encstr = 6;</code>
     *
     * <pre>
     *MD5后字符串
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getEncstrBytes() {
      Object ref = encstr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encstr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string encver = 7;
    public static final int ENCVER_FIELD_NUMBER = 7;
    private Object encver_;
    */
/**
     * <code>required string encver = 7;</code>
     *
     * <pre>
     *加密版本
     * </pre>
     *//*

    public boolean hasEncver() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    */
/**
     * <code>required string encver = 7;</code>
     *
     * <pre>
     *加密版本
     * </pre>
     *//*

    public String getEncver() {
      Object ref = encver_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encver_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string encver = 7;</code>
     *
     * <pre>
     *加密版本
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getEncverBytes() {
      Object ref = encver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        encver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 advertiserId = 8;
    public static final int ADVERTISERID_FIELD_NUMBER = 8;
    private int advertiserId_;
    */
/**
     * <code>required int32 advertiserId = 8;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     *//*

    public boolean hasAdvertiserId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    */
/**
     * <code>required int32 advertiserId = 8;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     *//*

    public int getAdvertiserId() {
      return advertiserId_;
    }

    // required string appType = 9;
    public static final int APPTYPE_FIELD_NUMBER = 9;
    private Object appType_;
    */
/**
     * <code>required string appType = 9;</code>
     *
     * <pre>
     *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
     * </pre>
     *//*

    public boolean hasAppType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    */
/**
     * <code>required string appType = 9;</code>
     *
     * <pre>
     *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
     * </pre>
     *//*

    public String getAppType() {
      Object ref = appType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appType_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string appType = 9;</code>
     *
     * <pre>
     *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getAppTypeBytes() {
      Object ref = appType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string convType = 10;
    public static final int CONVTYPE_FIELD_NUMBER = 10;
    private Object convType_;
    */
/**
     * <code>required string convType = 10;</code>
     *
     * <pre>
     *转化行为
     * </pre>
     *//*

    public boolean hasConvType() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    */
/**
     * <code>required string convType = 10;</code>
     *
     * <pre>
     *转化行为
     * </pre>
     *//*

    public String getConvType() {
      Object ref = convType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          convType_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string convType = 10;</code>
     *
     * <pre>
     *转化行为
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getConvTypeBytes() {
      Object ref = convType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        convType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 appKey = 11;
    public static final int APPKEY_FIELD_NUMBER = 11;
    private int appKey_;
    */
/**
     * <code>required int32 appKey = 11;</code>
     *
     * <pre>
     *appkey
     * </pre>
     *//*

    public boolean hasAppKey() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    */
/**
     * <code>required int32 appKey = 11;</code>
     *
     * <pre>
     *appkey
     * </pre>
     *//*

    public int getAppKey() {
      return appKey_;
    }

    // required string devId = 12;
    public static final int DEVID_FIELD_NUMBER = 12;
    private Object devId_;
    */
/**
     * <code>required string devId = 12;</code>
     *
     * <pre>
     *device id
     * </pre>
     *//*

    public boolean hasDevId() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    */
/**
     * <code>required string devId = 12;</code>
     *
     * <pre>
     *device id
     * </pre>
     *//*

    public String getDevId() {
      Object ref = devId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          devId_ = s;
        }
        return s;
      }
    }
    */
/**
     * <code>required string devId = 12;</code>
     *
     * <pre>
     *device id
     * </pre>
     *//*

    public com.google.protobuf.ByteString
        getDevIdBytes() {
      Object ref = devId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      clickId_ = "";
      muid_ = "";
      appid_ = 0;
      convTime_ = "";
      clientIp_ = "";
      encstr_ = "";
      encver_ = "";
      advertiserId_ = 0;
      appType_ = "";
      convType_ = "";
      appKey_ = 0;
      devId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClickId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConvTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncstr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncver()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdvertiserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConvType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDevId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClickIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, appid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getConvTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getClientIpBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getEncstrBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getEncverBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, advertiserId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getAppTypeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getConvTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, appKey_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getDevIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClickIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMuidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, appid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getConvTimeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getClientIpBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getEncstrBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getEncverBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, advertiserId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getAppTypeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getConvTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, appKey_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getDevIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    */
/**
     * Protobuf type {@code postBody}
     *//*

    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements suishen.wolves.gdt.feedback.vo.GdtPostBody.postBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return suishen.wolves.gdt.feedback.vo.GdtPostBody.internal_static_postBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return suishen.wolves.gdt.feedback.vo.GdtPostBody.internal_static_postBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody.class, suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody.Builder.class);
      }

      // Construct using suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clickId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        muid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        appid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        convTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        clientIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        encstr_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        encver_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        advertiserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        appType_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        convType_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        appKey_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        devId_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return suishen.wolves.gdt.feedback.vo.GdtPostBody.internal_static_postBody_descriptor;
      }

      public suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody getDefaultInstanceForType() {
        return suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody.getDefaultInstance();
      }

      public suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody build() {
        suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody buildPartial() {
        suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody result = new suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clickId_ = clickId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.muid_ = muid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.appid_ = appid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.convTime_ = convTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.clientIp_ = clientIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.encstr_ = encstr_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.encver_ = encver_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.advertiserId_ = advertiserId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.appType_ = appType_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.convType_ = convType_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.appKey_ = appKey_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.devId_ = devId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody) {
          return mergeFrom((suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody other) {
        if (other == suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody.getDefaultInstance()) return this;
        if (other.hasClickId()) {
          bitField0_ |= 0x00000001;
          clickId_ = other.clickId_;
          onChanged();
        }
        if (other.hasMuid()) {
          bitField0_ |= 0x00000002;
          muid_ = other.muid_;
          onChanged();
        }
        if (other.hasAppid()) {
          setAppid(other.getAppid());
        }
        if (other.hasConvTime()) {
          bitField0_ |= 0x00000008;
          convTime_ = other.convTime_;
          onChanged();
        }
        if (other.hasClientIp()) {
          bitField0_ |= 0x00000010;
          clientIp_ = other.clientIp_;
          onChanged();
        }
        if (other.hasEncstr()) {
          bitField0_ |= 0x00000020;
          encstr_ = other.encstr_;
          onChanged();
        }
        if (other.hasEncver()) {
          bitField0_ |= 0x00000040;
          encver_ = other.encver_;
          onChanged();
        }
        if (other.hasAdvertiserId()) {
          setAdvertiserId(other.getAdvertiserId());
        }
        if (other.hasAppType()) {
          bitField0_ |= 0x00000100;
          appType_ = other.appType_;
          onChanged();
        }
        if (other.hasConvType()) {
          bitField0_ |= 0x00000200;
          convType_ = other.convType_;
          onChanged();
        }
        if (other.hasAppKey()) {
          setAppKey(other.getAppKey());
        }
        if (other.hasDevId()) {
          bitField0_ |= 0x00000800;
          devId_ = other.devId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClickId()) {

          return false;
        }
        if (!hasMuid()) {

          return false;
        }
        if (!hasAppid()) {

          return false;
        }
        if (!hasConvTime()) {

          return false;
        }
        if (!hasClientIp()) {

          return false;
        }
        if (!hasEncstr()) {

          return false;
        }
        if (!hasEncver()) {

          return false;
        }
        if (!hasAdvertiserId()) {

          return false;
        }
        if (!hasAppType()) {

          return false;
        }
        if (!hasConvType()) {

          return false;
        }
        if (!hasAppKey()) {

          return false;
        }
        if (!hasDevId()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (suishen.wolves.gdt.feedback.vo.GdtPostBody.postBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string clickId = 1;
      private Object clickId_ = "";
      */
/**
       * <code>required string clickId = 1;</code>
       *
       * <pre>
       *点击ID
       * </pre>
       *//*

      public boolean hasClickId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      */
/**
       * <code>required string clickId = 1;</code>
       *
       * <pre>
       *点击ID
       * </pre>
       *//*

      public String getClickId() {
        Object ref = clickId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clickId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string clickId = 1;</code>
       *
       * <pre>
       *点击ID
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getClickIdBytes() {
        Object ref = clickId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clickId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string clickId = 1;</code>
       *
       * <pre>
       *点击ID
       * </pre>
       *//*

      public Builder setClickId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clickId_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string clickId = 1;</code>
       *
       * <pre>
       *点击ID
       * </pre>
       *//*

      public Builder clearClickId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clickId_ = getDefaultInstance().getClickId();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string clickId = 1;</code>
       *
       * <pre>
       *点击ID
       * </pre>
       *//*

      public Builder setClickIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clickId_ = value;
        onChanged();
        return this;
      }

      // required string muid = 2;
      private Object muid_ = "";
      */
/**
       * <code>required string muid = 2;</code>
       *
       * <pre>
       *设备id
       * </pre>
       *//*

      public boolean hasMuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      */
/**
       * <code>required string muid = 2;</code>
       *
       * <pre>
       *设备id
       * </pre>
       *//*

      public String getMuid() {
        Object ref = muid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          muid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string muid = 2;</code>
       *
       * <pre>
       *设备id
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getMuidBytes() {
        Object ref = muid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          muid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string muid = 2;</code>
       *
       * <pre>
       *设备id
       * </pre>
       *//*

      public Builder setMuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        muid_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string muid = 2;</code>
       *
       * <pre>
       *设备id
       * </pre>
       *//*

      public Builder clearMuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        muid_ = getDefaultInstance().getMuid();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string muid = 2;</code>
       *
       * <pre>
       *设备id
       * </pre>
       *//*

      public Builder setMuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        muid_ = value;
        onChanged();
        return this;
      }

      // required int32 appid = 3;
      private int appid_ ;
      */
/**
       * <code>required int32 appid = 3;</code>
       *
       * <pre>
       *Android为应用宝ID
       * </pre>
       *//*

      public boolean hasAppid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      */
/**
       * <code>required int32 appid = 3;</code>
       *
       * <pre>
       *Android为应用宝ID
       * </pre>
       *//*

      public int getAppid() {
        return appid_;
      }
      */
/**
       * <code>required int32 appid = 3;</code>
       *
       * <pre>
       *Android为应用宝ID
       * </pre>
       *//*

      public Builder setAppid(int value) {
        bitField0_ |= 0x00000004;
        appid_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required int32 appid = 3;</code>
       *
       * <pre>
       *Android为应用宝ID
       * </pre>
       *//*

      public Builder clearAppid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        appid_ = 0;
        onChanged();
        return this;
      }

      // required string convTime = 4;
      private Object convTime_ = "";
      */
/**
       * <code>required string convTime = 4;</code>
       *
       * <pre>
       *转化发生时间,秒级
       * </pre>
       *//*

      public boolean hasConvTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      */
/**
       * <code>required string convTime = 4;</code>
       *
       * <pre>
       *转化发生时间,秒级
       * </pre>
       *//*

      public String getConvTime() {
        Object ref = convTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          convTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string convTime = 4;</code>
       *
       * <pre>
       *转化发生时间,秒级
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getConvTimeBytes() {
        Object ref = convTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          convTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string convTime = 4;</code>
       *
       * <pre>
       *转化发生时间,秒级
       * </pre>
       *//*

      public Builder setConvTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        convTime_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string convTime = 4;</code>
       *
       * <pre>
       *转化发生时间,秒级
       * </pre>
       *//*

      public Builder clearConvTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        convTime_ = getDefaultInstance().getConvTime();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string convTime = 4;</code>
       *
       * <pre>
       *转化发生时间,秒级
       * </pre>
       *//*

      public Builder setConvTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        convTime_ = value;
        onChanged();
        return this;
      }

      // required string clientIp = 5;
      private Object clientIp_ = "";
      */
/**
       * <code>required string clientIp = 5;</code>
       *
       * <pre>
       *转化发生用户的客户端IP
       * </pre>
       *//*

      public boolean hasClientIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      */
/**
       * <code>required string clientIp = 5;</code>
       *
       * <pre>
       *转化发生用户的客户端IP
       * </pre>
       *//*

      public String getClientIp() {
        Object ref = clientIp_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clientIp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string clientIp = 5;</code>
       *
       * <pre>
       *转化发生用户的客户端IP
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getClientIpBytes() {
        Object ref = clientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string clientIp = 5;</code>
       *
       * <pre>
       *转化发生用户的客户端IP
       * </pre>
       *//*

      public Builder setClientIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientIp_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string clientIp = 5;</code>
       *
       * <pre>
       *转化发生用户的客户端IP
       * </pre>
       *//*

      public Builder clearClientIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        clientIp_ = getDefaultInstance().getClientIp();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string clientIp = 5;</code>
       *
       * <pre>
       *转化发生用户的客户端IP
       * </pre>
       *//*

      public Builder setClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        clientIp_ = value;
        onChanged();
        return this;
      }

      // required string encstr = 6;
      private Object encstr_ = "";
      */
/**
       * <code>required string encstr = 6;</code>
       *
       * <pre>
       *MD5后字符串
       * </pre>
       *//*

      public boolean hasEncstr() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      */
/**
       * <code>required string encstr = 6;</code>
       *
       * <pre>
       *MD5后字符串
       * </pre>
       *//*

      public String getEncstr() {
        Object ref = encstr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          encstr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string encstr = 6;</code>
       *
       * <pre>
       *MD5后字符串
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getEncstrBytes() {
        Object ref = encstr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          encstr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string encstr = 6;</code>
       *
       * <pre>
       *MD5后字符串
       * </pre>
       *//*

      public Builder setEncstr(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        encstr_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string encstr = 6;</code>
       *
       * <pre>
       *MD5后字符串
       * </pre>
       *//*

      public Builder clearEncstr() {
        bitField0_ = (bitField0_ & ~0x00000020);
        encstr_ = getDefaultInstance().getEncstr();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string encstr = 6;</code>
       *
       * <pre>
       *MD5后字符串
       * </pre>
       *//*

      public Builder setEncstrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        encstr_ = value;
        onChanged();
        return this;
      }

      // required string encver = 7;
      private Object encver_ = "";
      */
/**
       * <code>required string encver = 7;</code>
       *
       * <pre>
       *加密版本
       * </pre>
       *//*

      public boolean hasEncver() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      */
/**
       * <code>required string encver = 7;</code>
       *
       * <pre>
       *加密版本
       * </pre>
       *//*

      public String getEncver() {
        Object ref = encver_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          encver_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string encver = 7;</code>
       *
       * <pre>
       *加密版本
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getEncverBytes() {
        Object ref = encver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          encver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string encver = 7;</code>
       *
       * <pre>
       *加密版本
       * </pre>
       *//*

      public Builder setEncver(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        encver_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string encver = 7;</code>
       *
       * <pre>
       *加密版本
       * </pre>
       *//*

      public Builder clearEncver() {
        bitField0_ = (bitField0_ & ~0x00000040);
        encver_ = getDefaultInstance().getEncver();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string encver = 7;</code>
       *
       * <pre>
       *加密版本
       * </pre>
       *//*

      public Builder setEncverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        encver_ = value;
        onChanged();
        return this;
      }

      // required int32 advertiserId = 8;
      private int advertiserId_ ;
      */
/**
       * <code>required int32 advertiserId = 8;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       *//*

      public boolean hasAdvertiserId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      */
/**
       * <code>required int32 advertiserId = 8;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       *//*

      public int getAdvertiserId() {
        return advertiserId_;
      }
      */
/**
       * <code>required int32 advertiserId = 8;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       *//*

      public Builder setAdvertiserId(int value) {
        bitField0_ |= 0x00000080;
        advertiserId_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required int32 advertiserId = 8;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       *//*

      public Builder clearAdvertiserId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        advertiserId_ = 0;
        onChanged();
        return this;
      }

      // required string appType = 9;
      private Object appType_ = "";
      */
/**
       * <code>required string appType = 9;</code>
       *
       * <pre>
       *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
       * </pre>
       *//*

      public boolean hasAppType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      */
/**
       * <code>required string appType = 9;</code>
       *
       * <pre>
       *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
       * </pre>
       *//*

      public String getAppType() {
        Object ref = appType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          appType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string appType = 9;</code>
       *
       * <pre>
       *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getAppTypeBytes() {
        Object ref = appType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          appType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string appType = 9;</code>
       *
       * <pre>
       *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
       * </pre>
       *//*

      public Builder setAppType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        appType_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string appType = 9;</code>
       *
       * <pre>
       *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
       * </pre>
       *//*

      public Builder clearAppType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        appType_ = getDefaultInstance().getAppType();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string appType = 9;</code>
       *
       * <pre>
       *app类型;iOS 应用取值为 IOS，Android 应用取值为 ANDROID
       * </pre>
       *//*

      public Builder setAppTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        appType_ = value;
        onChanged();
        return this;
      }

      // required string convType = 10;
      private Object convType_ = "";
      */
/**
       * <code>required string convType = 10;</code>
       *
       * <pre>
       *转化行为
       * </pre>
       *//*

      public boolean hasConvType() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      */
/**
       * <code>required string convType = 10;</code>
       *
       * <pre>
       *转化行为
       * </pre>
       *//*

      public String getConvType() {
        Object ref = convType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          convType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string convType = 10;</code>
       *
       * <pre>
       *转化行为
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getConvTypeBytes() {
        Object ref = convType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          convType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string convType = 10;</code>
       *
       * <pre>
       *转化行为
       * </pre>
       *//*

      public Builder setConvType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        convType_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string convType = 10;</code>
       *
       * <pre>
       *转化行为
       * </pre>
       *//*

      public Builder clearConvType() {
        bitField0_ = (bitField0_ & ~0x00000200);
        convType_ = getDefaultInstance().getConvType();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string convType = 10;</code>
       *
       * <pre>
       *转化行为
       * </pre>
       *//*

      public Builder setConvTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        convType_ = value;
        onChanged();
        return this;
      }

      // required int32 appKey = 11;
      private int appKey_ ;
      */
/**
       * <code>required int32 appKey = 11;</code>
       *
       * <pre>
       *appkey
       * </pre>
       *//*

      public boolean hasAppKey() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      */
/**
       * <code>required int32 appKey = 11;</code>
       *
       * <pre>
       *appkey
       * </pre>
       *//*

      public int getAppKey() {
        return appKey_;
      }
      */
/**
       * <code>required int32 appKey = 11;</code>
       *
       * <pre>
       *appkey
       * </pre>
       *//*

      public Builder setAppKey(int value) {
        bitField0_ |= 0x00000400;
        appKey_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required int32 appKey = 11;</code>
       *
       * <pre>
       *appkey
       * </pre>
       *//*

      public Builder clearAppKey() {
        bitField0_ = (bitField0_ & ~0x00000400);
        appKey_ = 0;
        onChanged();
        return this;
      }

      // required string devId = 12;
      private Object devId_ = "";
      */
/**
       * <code>required string devId = 12;</code>
       *
       * <pre>
       *device id
       * </pre>
       *//*

      public boolean hasDevId() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      */
/**
       * <code>required string devId = 12;</code>
       *
       * <pre>
       *device id
       * </pre>
       *//*

      public String getDevId() {
        Object ref = devId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          devId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      */
/**
       * <code>required string devId = 12;</code>
       *
       * <pre>
       *device id
       * </pre>
       *//*

      public com.google.protobuf.ByteString
          getDevIdBytes() {
        Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      */
/**
       * <code>required string devId = 12;</code>
       *
       * <pre>
       *device id
       * </pre>
       *//*

      public Builder setDevId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        devId_ = value;
        onChanged();
        return this;
      }
      */
/**
       * <code>required string devId = 12;</code>
       *
       * <pre>
       *device id
       * </pre>
       *//*

      public Builder clearDevId() {
        bitField0_ = (bitField0_ & ~0x00000800);
        devId_ = getDefaultInstance().getDevId();
        onChanged();
        return this;
      }
      */
/**
       * <code>required string devId = 12;</code>
       *
       * <pre>
       *device id
       * </pre>
       *//*

      public Builder setDevIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        devId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:postBody)
    }

    static {
      defaultInstance = new postBody(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:postBody)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_postBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_postBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n-suishen/wolves/gdt/feedback/vo/postBod" +
      "y.proto\"\324\001\n\010postBody\022\017\n\007clickId\030\001 \002(\t\022\014\n" +
      "\004muid\030\002 \002(\t\022\r\n\005appid\030\003 \002(\005\022\020\n\010convTime\030\004" +
      " \002(\t\022\020\n\010clientIp\030\005 \002(\t\022\016\n\006encstr\030\006 \002(\t\022\016" +
      "\n\006encver\030\007 \002(\t\022\024\n\014advertiserId\030\010 \002(\005\022\017\n\007" +
      "appType\030\t \002(\t\022\020\n\010convType\030\n \002(\t\022\016\n\006appKe" +
      "y\030\013 \002(\005\022\r\n\005devId\030\014 \002(\tB-\n\036suishen.wolves" +
      ".gdt.feedback.voB\013GdtPostBody"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_postBody_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_postBody_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_postBody_descriptor,
              new String[] { "ClickId", "Muid", "Appid", "ConvTime", "ClientIp", "Encstr", "Encver", "AdvertiserId", "AppType", "ConvType", "AppKey", "DevId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
*/
